/* automatically generated by rust-bindgen */

#[doc = " Type of stream callback functions."]
#[doc = " \\param stream The stream as passed to ::cudaStreamAddCallback, may be NULL."]
#[doc = " \\param status ::cudaSuccess or any persistent error on the stream."]
#[doc = " \\param userData User parameter provided at registration."]
pub type cudaStreamCallback_t = ::std::option::Option<
    unsafe extern "C" fn(
        stream: cudaStream_t,
        status: cudaError_t,
        userData: *mut ::std::os::raw::c_void,
    ),
>;
